Bootstrap: docker
From: scientificlinux/sl:7

% help
Recipe for a Singularity container running Vaa3d and various wrapper scripts

%labels
AUTHOR Konrad Rokicki
VERSION 1.0

%files
./scripts /opt/scripts

%post
cd /opt # Install all software in /opt

echo "Installing Vaa3d"
# Prereqs for Vaa3d
yum install -y mesa-libGLU qt qt-x11 libXv numactl-libs
# Install Vaa3d
VAA3D_FILE=vaa3d-redhat-mark11.tgz
curl -s http://workstation.int.janelia.org/files/tools/{$VAA3D_FILE} -o '#1'
tar xvf $VAA3D_FILE && /bin/rm -f $VAA3D_FILE
ln -s /opt/vaa3d-redhat-mark11 Vaa3D

echo "Installing other dependencies"
EPEL_FILE=epel-release-latest-7.noarch.rpm
curl -s http://dl.fedoraproject.org/pub/epel/{$EPEL_FILE} -o '#1'
rpm -ivh $EPEL_FILE && /bin/rm -f $EPEL_FILE
yum install -y pbzip2

echo "Fixing permissions"
chown -R root:root /opt/*
chmod -R g+r /opt/*

%apprun vaa3d
/opt/Vaa3d/vaa3d "$@"
%apphelp vaa3d
Invoke vaa3d

%apprun channelMap
/opt/scripts/channelMap.sh "$@"
%apphelp channelMap
Wrapper for mapchannels Vaa3d command

%apprun convert
/opt/scripts/convert.sh "$@"
%apphelp convert
Convert file format, including handling bz/pbzip2 extensions

%apprun flipZ
/opt/scripts/flipZ.sh "$@"
%apphelp flipZ
Flip stack around the diagonal from the upper left to the lower right

%apprun splitChannels
/opt/scripts/splitChannels.sh "$@"
%apphelp splitChannels
Take single stack input and create an output file for each channel

