Bootstrap: docker
From: scientificlinux/sl:7

%help
Recipe for a Singularity container running color depth projection tools

%labels
AUTHOR Hideo Otsuna
VERSION 1.0

%files
./fiji_macros /opt/fiji_macros
./fiji_plugins /opt/fiji_plugins
./fiji_luts /opt/fiji_luts

%post
cd /opt # Install all software in /opt

echo "Installing Fiji"
# Prereqs for Fiji
yum install -y libXtst-devel libXrender
# Install Fiji
FIJI_FILE=fiji-1.52c.tgz
curl -sLL http://workstation.int.janelia.org/files/fiji/{$FIJI_FILE} -o '#1'
tar xvfz $FIJI_FILE && /bin/rm -rf $FIJI_FILE
mv Fiji.app Fiji

echo "Installing Fiji plugins"
PLUGINS_SOURCE=/opt/fiji_plugins
PLUGINS_TARGET=/opt/Fiji/plugins
cp -R $PLUGINS_SOURCE/* $PLUGINS_TARGET && /bin/rm -rf $PLUGINS_SOURCE

echo "Installing Fiji LUTs"
LUTS_SOURCE=/opt/fiji_luts
LUTS_TARGET=/opt/Fiji/luts
cp -R $LUTS_SOURCE/* $LUTS_TARGET && /bin/rm -rf $LUTS_SOURCE

echo "Fixing permissions"
chown -R root:root /opt/*
chmod -R g+r /opt/*

%apprun generate_cdm
/opt/Fiji/ImageJ-linux64 -macro /opt/fiji_macros/Color_Depth_MIP_batch_For_Pipeline.ijm "$@"
%apphelp generate_cdm
Generate a color depth MIP for the given input. The parameter is structured like this:
"<input_dir>,<input_filename>,<temp_dir>,<mask_dir>,<anatomical_area>"
Paths must be / terminated.

