Bootstrap: docker
From: scientificlinux/sl:7

% help
Recipe for a singuality container for running 20x/40x brain aligner against the JRC2018 template

%labels
AUTHOR Konrad Rokicki
VERSION 1.0

%files
./aligner /opt/aligner

%post
cd /opt # Install all software in /opt

echo "Installing Vaa3d"
# Prereqs for Vaa3d
yum install -y mesa-libGLU qt qt-x11 libXv numactl-libs
# Install Vaa3d
VAA3D_FILE=vaa3d-redhat-mark10.tgz
curl -s http://workstation.int.janelia.org/files/tools/{$VAA3D_FILE} -o '#1'
tar xvf $VAA3D_FILE && /bin/rm -f $VAA3D_FILE
ln -s /opt/vaa3d-redhat-mark10 Vaa3D

echo "Installing Fiji"
# Prereqs for Fiji
yum install -y libXtst-devel libXrender
# Install Fiji
FIJI_FILE=fiji-1.52c.tgz
curl -s http://workstation.int.janelia.org/files/fiji/{$FIJI_FILE} -o '#1'
tar xvfz $FIJI_FILE && /bin/rm -rf $FIJI_FILE
rm -rf Fiji
mv Fiji.app Fiji

echo "Installing Fiji plugins"
PLUGINS_SOURCE=/opt/aligner/Brain_Aligner_Fiji_Plugins
PLUGINS_TARGET=/opt/Fiji/plugins
cp -R $PLUGINS_SOURCE/* $PLUGINS_TARGET && /bin/rm -rf $PLUGINS_SOURCE

echo "Installing CMTK"
# Prereqs for CMTK
yum install -y fftw-libs-double
# Install CMTK
CMTK_FILE=cmtk-20171001-sl7avx.tgz
curl -s http://workstation.int.janelia.org/files/tools/{$CMTK_FILE} -o '#1'
tar xvf $CMTK_FILE && /bin/rm -f $CMTK_FILE
ln -s cmtk-scm-2017-10-01 CMTK

echo "Installing dependencies"
EPEL_FILE=epel-release-latest-7.noarch.rpm
curl -s http://dl.fedoraproject.org/pub/epel/{$EPEL_FILE} -o '#1'
rpm -ivh $EPEL_FILE && /bin/rm -f $EPEL_FILE
yum install -y python-pip jq bc
pip install yq

echo "Fixing permissions"
chown -R root:root /opt/*
chmod -R g+r /opt/*

%apprun align_ol_intact
/opt/aligner/20xBrain_Align_CMTK.sh $@ "Intact"
%apphelp align_ol_intact
Uses the CMTK aligner to align a brain with optic lobes to the JRC2018 template

%apprun align_both_ol_missing
/opt/aligner/20xBrain_Align_CMTK.sh $@ "Both_OL_missing (40x)"
%apphelp align_both_old_missing
Uses the CMTK aligner to align a brain missing its optic lobes to the JRC2018 template

%apprun align_ol_unknown
/opt/aligner/20xBrain_Align_CMTK.sh $@ "Unknown"
%apphelp align_ol_unknown
Uses the CMTK aligner to align a brain with unknown optic lobe status to the JRC2018 template. Use this for all 20x brains.

